# lowest severity of logs to be shown, Debug < Info < Warning < Error
severity = "I"

[connect]
  IRC        = true
  Matrix     = true
  Mattermost = false
  Telegram   = true
  XMPP       = false

[IRC]
  host = "irc.libera.chat"
  port = "6667"
  chan = "#tutbot-testing"
  nick = "echobot"
  name = "echobot"

[Matrix]
  token = ""
  name = "@example:matrix.org"
  homeserver = "matrix.org"
  # "since" param to make the first sync
  # can be next_batch of a previous sync
  # if empty, 5 events will be gotten from each room
  since = ""

[Mattermost]
  host = ""
  port = 0
  path = ""
  nick = ""
  password = ""

[Telegram]
  token = ""
  # 0 to firstly get recent messages
  offset = 0

[XMPP]
  host = "test.pontarius.org"
  nick = ""
  password = ""

[defaults]
  repeatCount = 1

[messages]
  help = """I repeat everything you write, except:
/help   -> print this message
/repeat -> show and change your repeat count"""
  repeat1 = "your current repeat count is "
  repeat2 = "\nenter your next repeat count (0 to 5):"
  invalid = "invalid, again please:"
